<header>
    <h2>Create Post</h2>
</header>

<form class="post" action="/posts/create" method="POST">
    <section class="title">
        <label>
            Title
            <input type="text" name="post[title]" placeholder="For example: Why rainbow-shitting Unicorns rock">
        </label>
    </section>

    <section class="content">
        <label for="content">Content</label>
        <textarea id="content" name="post[content]" placeholder="Put your content here."></textarea>
    </section>

    <footer>
        <input type="submit" value="Create Post!">
        or <a href="/">Cancel</a>
    </footer>
</form>
