<?php $this->contentFor('title') ?>
Edit Post
<?php $this->endContentFor() ?>

<form class="post" action="<?= $this->urlFor('posts_update', ['params' => ['id' => $this->post['_id']]]); ?>" method="POST">
    <section class="title">
        <label>
            Title
            <input name="post[title]" value="<?= $this->post['title'] ?>">
        </label>
    </section>

    <section class="content">
        <label for="content">Content</label>
        <textarea id="content" name="post[content]"><?= $this->post['content'] ?></textarea>
    </section>

    <footer>
        <input type="submit" value="Save this Post!" class="primary">
        or <a href="<?= $this->urlFor('posts_show', ['params' => ['id' => $this->post['_id']]]); ?>">Cancel</a>
    </footer>

    <input type="hidden" name="_method" value="PUT">
</form>
