<form class="post" action="/posts/edit/<?= $this->post['_id'] ?>" method="POST">
    <section class="title">
        <label>
            Title
            <input name="post[title]" value="<?= $this->post['title'] ?>">
        </label>
    </section>

    <section class="content">
        <label for="content">Content</label>
        <textarea id="content" name="post[content]"><?= $this->post['content'] ?></textarea>
    </section>

    <footer>
        <input type="submit" value="Save this Post!">
        or <a href="/posts/show/<?= $this->post['_id'] ?>">Cancel</a>
    </footer>
</form>
