<article>
    <header>
        <h1><?= $this->post['title'] ?></h1>
        Created <time><?= date('d/m/Y H:i', $this->post['created']->sec) ?></time>

        <?php if (isset($this->post['updated'])): ?>
        , Last Updated <time><?= date('d/m/Y H:i', $this->post['updated']->sec) ?></time>
        <?php endif ?>
    </header>

    <section class="content">
        <?= $this->post['content'] ?>
    </section>

    <footer>
        <a href="/posts/edit/<?= $this->post['_id'] ?>">Edit this Post</a>
        <a href="/posts/delete/<?= $this->post['_id'] ?>">Delete</a>
    </footer>
</article>
