<!DOCTYPE html>
<html>
    <head>
        <title>
            <?= $this->block('title') ?>
        </title>

        <?= $this->assetLinkTag('screen.less') ?>
    </head>
    <body>
        <header role="banner">
            <h1><a href="/">My awesome Blog</a></h1>
        </header>

        <section id="flash">
            <?php foreach ($this->flash()->get('notice', []) as $flash): ?>
            <div class="flash-notice">
                <?= $flash ?>
            </div>
            <?php endforeach ?>
        </section>

        <section role="main">
            <?= $this->block('content') ?>
        </section>

        <footer>
            <p>Built with <a href="http://github.com/CHH/spark">Spark Framework</a></p>
        </footer>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <?= $this->assetLinkTag('application.coffee') ?>
    </body>
</html>
