<!DOCTYPE html>
<html>
    <head>
        <title>
            <?= $this->block('title') ?>
        </title>

        <?= $this->assetLinkTag('screen.less') ?>
    </head>
    <body>
        <h1><a href="/">My awesome Blog</a></h1>

        <?php foreach ($this->flash()->get('notice', []) as $flash): ?>
        <div class="flash-notice">
            <?= $flash ?>
        </div>
        <?php endforeach ?>

        <?= $this->block('content') ?>
    </body>
</html>
